const collections: Collection[] = [
  {
    id: 1,
    name: 'Science Fiction Classics',
    description:
      'A timeless anthology of groundbreaking and visionary sci-fi masterpieces.',
    books: [
      {
        id: 1,
        title: 'Dune',
        subtitle: 'The Spice Must Flow',
        publication_year: 1965,
        publisher: 'Chilton Books',
        description:
          'A science fiction epic that explores politics, religion, and ecology in a distant future.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 4,
        location: 'Shelf A3',
      },
      {
        id: 2,
        title: 'Neuromancer',
        subtitle: 'A Cyberpunk Classic',
        publication_year: 1984,
        publisher: 'Ace Books',
        description:
          'A genre-defining cyberpunk novel that follows a washed-up hacker in a high-tech dystopia.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf B2',
      },
      {
        id: 3,
        title: 'Foundation',
        subtitle: 'The Foundation Trilogy',
        publication_year: 1951,
        publisher: 'Gnome Press',
        description:
          'A sweeping saga about the fall and rebirth of a galactic civilization.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 3,
        location: 'Shelf A1',
      },
      {
        id: 4,
        title: "Ender's Game",
        subtitle: 'The Battle School',
        publication_year: 1985,
        publisher: 'Tor Books',
        description:
          'A military science fiction novel about children trained for interstellar warfare.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'unread',
        rating: 2,
        location: 'Shelf A4',
      },
      {
        id: 5,
        title: 'The Left Hand of Darkness',
        subtitle: 'An Ambisexual Journey',
        publication_year: 1969,
        publisher: 'Ace Books',
        description:
          'A groundbreaking exploration of gender and society on an alien world.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf B1',
      },
      {
        id: 6,
        title: 'Snow Crash',
        subtitle: 'The Metaverse Awaits',
        publication_year: 1992,
        publisher: 'Bantam Books',
        description:
          'A fast-paced adventure through both virtual and real worlds.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 5,
        location: 'Shelf B3',
      },
      {
        id: 7,
        title: 'Hyperion',
        subtitle: 'The Shrike Pilgimage',
        publication_year: 1989,
        publisher: 'Doubleday',
        description:
          'A complex tale of pilgrims on a journey to meet a legendary creature.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 0,
        location: 'Shelf A2',
      },
      {
        id: 8,
        title: 'The Forever War',
        subtitle: 'Time Dilation and Combat',
        publication_year: 1974,
        publisher: "St. Martin's Press",
        description:
          'A military science fiction novel about the effects of time dilation on warfare.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'unread',
        rating: 0,
        location: 'Shelf B4',
      },
      {
        id: 9,
        title: "Childhood's End",
        subtitle: 'The Overlords Arrive',
        publication_year: 1953,
        publisher: 'Ballantine Books',
        description:
          "A story about mysterious alien overlords who guide humanity's evolution.",
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 5,
        location: 'Shelf A5',
      },
      {
        id: 10,
        title: 'The Stars My Destination',
        subtitle: 'Count of Monte Cristo in Space',
        publication_year: 1956,
        publisher: 'Galaxy Science Fiction',
        description:
          'A revenge story set in a future where humans can teleport.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 2,
        location: 'Shelf B5',
      },
      {
        id: 11,
        title: 'Ringworld',
        subtitle: 'The Great Ring',
        publication_year: 1970,
        publisher: 'Ballantine Books',
        description:
          'An expedition to explore a mysterious artificial ring around a distant star.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 3,
        location: 'Shelf B6',
      },
      {
        id: 12,
        title: 'The Kite Runner',
        subtitle: 'Redemption in Kabul',
        publication_year: 2003,
        publisher: 'Riverhead Books',
        description:
          'A powerful story of friendship, betrayal, and redemption in Afghanistan.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 4,
        location: 'Shelf D9',
      },
    ],
  },
  {
    id: 2,
    name: 'Modern Literary Fiction',
    description: 'Contemporary masterpieces that define modern literature.',
    books: [
      {
        id: 13,
        title: 'The Road',
        subtitle: 'A Journey Through the Apocalypse',
        publication_year: 2006,
        publisher: 'Alfred A. Knopf',
        description:
          'A father and son journey through a post-apocalyptic America.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 5,
        location: 'Shelf C1',
      },
      {
        id: 14,
        title: 'Cloud Atlas',
        subtitle: 'Six Interconnected Stories',
        publication_year: 2004,
        publisher: 'Sceptre',
        description:
          'A nested series of interconnected stories spanning centuries.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf C2',
      },
      {
        id: 15,
        title: 'Never Let Me Go',
        subtitle: 'Life at Hailsham',
        publication_year: 2005,
        publisher: 'Faber and Faber',
        description: 'A subtle exploration of humanity and mortality.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 4,
        location: 'Shelf C3',
      },
      {
        id: 16,
        title: '1Q84',
        subtitle: 'Two Moons in the Sky',
        publication_year: 2009,
        publisher: 'Shinchosha',
        description: 'A surreal journey through an alternate reality in Tokyo.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'unread',
        rating: 0,
        location: 'Shelf C4',
      },
      {
        id: 17,
        title: 'White Teeth',
        subtitle: 'A London Story',
        publication_year: 2000,
        publisher: 'Hamish Hamilton',
        description: 'A vibrant portrait of modern multicultural London.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 3,
        location: 'Shelf C5',
      },
      {
        id: 18,
        title: 'The Brief Wondrous Life of Oscar Wao',
        subtitle: 'Curse of the Fukú',
        publication_year: 2007,
        publisher: 'Riverhead Books',
        description: 'A multi-generational Dominican-American family saga.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 5,
        location: 'Shelf C6',
      },
      {
        id: 19,
        title: 'Life of Pi',
        subtitle: 'Lost at Sea',
        publication_year: 2001,
        publisher: 'Knopf Canada',
        description: 'A philosophical adventure of survival at sea.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 4,
        location: 'Shelf C7',
      },
      {
        id: 20,
        title: 'The Shadow of the Wind',
        subtitle: 'Cemetery of Forgotten Books',
        publication_year: 2001,
        publisher: 'Penguin Books',
        description: 'A mysterious tale set in post-war Barcelona.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf C8',
      },
      {
        id: 21,
        title: 'Atonement',
        subtitle: 'A Summer Day',
        publication_year: 2001,
        publisher: 'Jonathan Cape',
        description: 'A story of love, war, and the burden of guilt.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'unread',
        rating: 0,
        location: 'Shelf C9',
      },
      {
        id: 22,
        title: 'The Corrections',
        subtitle: 'An American Family',
        publication_year: 2001,
        publisher: 'Farrar, Straus and Giroux',
        description: 'A portrait of a dysfunctional Midwestern family.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 3,
        location: 'Shelf D1',
      },
      {
        id: 23,
        title: 'American Gods',
        subtitle: 'Old Gods vs New',
        publication_year: 2001,
        publisher: 'William Morrow',
        description:
          'A dark fantasy about ancient and modern deities in America.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf D2',
      },
    ],
  },
  {
    id: 3,
    name: 'Mystery Thrillers',
    description: 'Edge-of-your-seat mystery and suspense novels.',
    books: [
      {
        id: 24,
        title: 'Gone Girl',
        subtitle: 'Marriage Gone Wrong',
        publication_year: 2012,
        publisher: 'Crown Publishing',
        description: 'A psychological thriller about a missing wife.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 4,
        location: 'Shelf E1',
      },
      {
        id: 25,
        title: 'The Girl with the Dragon Tattoo',
        subtitle: 'Millennium Series',
        publication_year: 2005,
        publisher: 'Norstedts Förlag',
        description: 'A journalist investigates a decades-old disappearance.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 5,
        location: 'Shelf E2',
      },
      {
        id: 26,
        title: 'The Da Vinci Code',
        subtitle: 'Symbols and Secrets',
        publication_year: 2003,
        publisher: 'Doubleday',
        description: 'A fast-paced hunt for religious artifacts.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 3,
        location: 'Shelf E3',
      },
      {
        id: 27,
        title: 'Sharp Objects',
        subtitle: 'Return to Wind Gap',
        publication_year: 2006,
        publisher: 'Shaye Areheart Books',
        description: 'A reporter returns home to investigate murders.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf E4',
      },
      {
        id: 28,
        title: 'In the Woods',
        subtitle: 'Dublin Murder Squad',
        publication_year: 2007,
        publisher: 'Viking Press',
        description: 'A detective faces his mysterious past.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'unread',
        rating: 0,
        location: 'Shelf E5',
      },
      {
        id: 29,
        title: 'The Silent Patient',
        subtitle: 'A Perfect Life',
        publication_year: 2019,
        publisher: 'Celadon Books',
        description: 'A woman stops speaking after shooting her husband.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf E6',
      },
    ],
  },
  {
    id: 4,
    name: 'Classic Philosophy',
    description: 'Fundamental works of philosophical thought.',
    books: [
      {
        id: 30,
        title: 'The Republic',
        subtitle: 'Justice and Society',
        publication_year: -380,
        publisher: 'Oxford University Press',
        description: "Plato's vision of the ideal state.",
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 5,
        location: 'Shelf F1',
      },
      {
        id: 31,
        title: 'Meditations',
        subtitle: 'Personal Writings',
        publication_year: 180,
        publisher: 'Penguin Classics',
        description: 'The private thoughts of a Roman emperor.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf F2',
      },
      {
        id: 32,
        title: 'Beyond Good and Evil',
        subtitle: 'Philosophy of the Future',
        publication_year: 1886,
        publisher: 'Vintage Books',
        description: "Nietzsche's critique of past philosophers.",
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'unread',
        rating: 0,
        location: 'Shelf F3',
      },
      {
        id: 33,
        title: 'Being and Time',
        subtitle: 'Fundamental Ontology',
        publication_year: 1927,
        publisher: 'Harper Perennial',
        description: 'An investigation into the meaning of Being.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 3,
        location: 'Shelf F4',
      },
    ],
  },
  {
    id: 5,
    name: 'Poetry Collections',
    description: 'Verses that moved generations.',
    books: [
      {
        id: 34,
        title: 'Leaves of Grass',
        subtitle: 'Song of Myself',
        publication_year: 1855,
        publisher: 'Dover Publications',
        description: "Whitman's celebration of American identity.",
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 5,
        location: 'Shelf G1',
      },
      {
        id: 35,
        title: 'The Waste Land',
        subtitle: 'April is the Cruellest Month',
        publication_year: 1922,
        publisher: 'Faber and Faber',
        description: "T.S. Eliot's modernist masterpiece.",
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf G2',
      },
      {
        id: 36,
        title: 'Ariel',
        subtitle: 'Last Poems',
        publication_year: 1965,
        publisher: 'Harper & Row',
        description: "Plath's final collection of poems.",
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 5,
        location: 'Shelf G3',
      },
      {
        id: 37,
        title: 'Selected Poems',
        subtitle: 'Pablo Neruda',
        publication_year: 1972,
        publisher: 'Grove Press',
        description: "A collection of Neruda's best works.",
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'unread',
        rating: 0,
        location: 'Shelf G4',
      },
    ],
  },
  {
    id: 6,
    name: 'Historical Biography',
    description: 'Lives that shaped our world.',
    books: [
      {
        id: 38,
        title: 'Team of Rivals',
        subtitle: 'Lincoln and His Cabinet',
        publication_year: 2005,
        publisher: 'Simon & Schuster',
        description: "Lincoln's political genius during the Civil War.",
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 5,
        location: 'Shelf H1',
      },
      {
        id: 39,
        title: 'Steve Jobs',
        subtitle: 'The Exclusive Biography',
        publication_year: 2011,
        publisher: 'Simon & Schuster',
        description: 'The life of the Apple co-founder.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf H2',
      },
      {
        id: 40,
        title: 'Long Walk to Freedom',
        subtitle: 'The Autobiography',
        publication_year: 1994,
        publisher: 'Little Brown & Co',
        description: "Nelson Mandela's journey to freedom.",
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 5,
        location: 'Shelf H3',
      },
    ],
  },
  {
    id: 7,
    name: 'Art History Essentials',
    description: 'Key works about artistic movements and masters.',
    books: [
      {
        id: 41,
        title: 'The Story of Art',
        subtitle: 'Art Through the Ages',
        publication_year: 1950,
        publisher: 'Phaidon Press',
        description: 'A comprehensive survey of art history.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf I1',
      },
      {
        id: 42,
        title: 'The Lives of Artists',
        subtitle: 'Renaissance Masters',
        publication_year: 1550,
        publisher: 'Oxford Press',
        description: "Vasari's biographical masterpiece.",
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'unread',
        rating: 0,
        location: 'Shelf I2',
      },
    ],
  },
  {
    id: 8,
    name: 'Chess Strategy',
    description: 'Advanced chess theory and gameplay.',
    books: [
      {
        id: 43,
        title: 'My System',
        subtitle: 'Chess Fundamentals',
        publication_year: 1925,
        publisher: 'Quality Chess',
        description: 'Revolutionary approach to chess strategy.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 5,
        location: 'Shelf J1',
      },
    ],
  },
  {
    id: 9,
    name: 'Garden Design',
    description: 'Landscape architecture and garden planning.',
    books: [
      {
        id: 44,
        title: 'The Well-Tempered Garden',
        subtitle: 'Four Seasons of Beauty',
        publication_year: 1970,
        publisher: 'Harper Collins',
        description: 'Classic guide to garden maintenance.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 3,
        location: 'Shelf K1',
      },
      {
        id: 45,
        title: 'Gardens Through Time',
        subtitle: 'Historical Perspectives',
        publication_year: 2005,
        publisher: 'Thames & Hudson',
        description: 'Evolution of garden design.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 4,
        location: 'Shelf K2',
      },
    ],
  },
  {
    id: 10,
    name: 'Music Theory',
    description: 'Understanding musical composition.',
    books: [
      {
        id: 46,
        title: 'Harmony',
        subtitle: 'Principles of Voice Leading',
        publication_year: 1948,
        publisher: 'Norton',
        description: 'Comprehensive guide to musical harmony.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf L1',
      },
    ],
  },
  {
    id: 11,
    name: 'Ancient Mythology',
    description: 'Tales of gods and heroes.',
    books: [
      {
        id: 47,
        title: "Bulfinch's Mythology",
        subtitle: 'The Age of Fable',
        publication_year: 1867,
        publisher: 'Dover',
        description: 'Classical myths retold.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 5,
        location: 'Shelf M1',
      },
      {
        id: 48,
        title: 'The Golden Bough',
        subtitle: 'A Study in Magic and Religion',
        publication_year: 1890,
        publisher: 'Macmillan',
        description: 'Comparative study of mythology.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'unread',
        rating: 0,
        location: 'Shelf M2',
      },
    ],
  },
  {
    id: 12,
    name: 'Wine Appreciation',
    description: 'Understanding and tasting fine wines.',
    books: [
      {
        id: 49,
        title: 'The World Atlas of Wine',
        subtitle: 'Global Wine Regions',
        publication_year: 2019,
        publisher: 'Mitchell Beazley',
        description: 'Comprehensive guide to wine regions.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf N1',
      },
      {
        id: 50,
        title: 'The Wine Bible',
        subtitle: 'From Grape to Glass',
        publication_year: 2015,
        publisher: 'Workman',
        description: 'Everything about wine appreciation.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 5,
        location: 'Shelf N2',
      },
    ],
  },
  {
    id: 13,
    name: 'Buddhist Philosophy',
    description: 'Essential teachings and practices.',
    books: [
      {
        id: 51,
        title: "The Heart of Buddha's Teaching",
        subtitle: 'Transforming Suffering',
        publication_year: 1998,
        publisher: 'Broadway Books',
        description: 'Core Buddhist concepts explained.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 5,
        location: 'Shelf O1',
      },
    ],
  },
  {
    id: 14,
    name: 'Architecture History',
    description: 'Evolution of building design.',
    books: [
      {
        id: 52,
        title: 'Towards a New Architecture',
        subtitle: 'Modern Principles',
        publication_year: 1923,
        publisher: 'Dover',
        description: "Le Corbusier's architectural manifesto.",
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 4,
        location: 'Shelf P1',
      },
      {
        id: 53,
        title: 'The Architecture of Happiness',
        subtitle: 'Building and Well-being',
        publication_year: 2006,
        publisher: 'Pantheon',
        description: 'Philosophy of architecture.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'unread',
        rating: 0,
        location: 'Shelf P2',
      },
    ],
  },
  {
    id: 15,
    name: 'Jazz History',
    description: 'Evolution of jazz music.',
    books: [
      {
        id: 54,
        title: 'The History of Jazz',
        subtitle: 'From Blues to Fusion',
        publication_year: 1997,
        publisher: 'Oxford Press',
        description: 'Comprehensive jazz evolution.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'reading',
        rating: 4,
        location: 'Shelf Q1',
      },
    ],
  },
  {
    id: 16,
    name: 'Photography Basics',
    description: 'Fundamentals of photography.',
    books: [
      {
        id: 55,
        title: 'On Photography',
        subtitle: 'Essays on the Image',
        publication_year: 1977,
        publisher: 'Farrar, Straus and Giroux',
        description: "Sontag's reflections on photography.",
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'read',
        rating: 5,
        location: 'Shelf R1',
      },
      {
        id: 56,
        title: 'Camera Lucida',
        subtitle: 'Reflections on Photography',
        publication_year: 1980,
        publisher: 'Hill and Wang',
        description: 'Theory of photography.',
        cover_image_url: 'https://via.placeholder.com/150',
        status: 'unread',
        rating: 0,
        location: 'Shelf R2',
      },
    ],
  },
]

export { collections }
// {
//     id: 2,
//     name: 'Philosophy & Thought',
//     description: 'Books that make you think deeper about life and existence.',
//     books: [
//       {
//         id: 3,
//         title: 'Meditations',
//         subtitle: 'Thoughts of a Roman Emperor',
//         publication_year: 180,
//         publisher: 'Unknown',
//         description:
//           'The personal reflections of Marcus Aurelius on Stoicism and personal virtue.',
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'reading',
//         rating: 4,
//         location: 'Desk',
//       },
//       {
//         id: 4,
//         title: 'The Republic',
//         subtitle: 'Justice, Order, and The Ideal State',
//         publication_year: -380,
//         publisher: 'Unknown',
//         description:
//           "Plato's famous dialogue on justice, political philosophy, and the ideal society.",
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'unread',
//         rating: 0,
//         location: 'Shelf C1',
//       },
//       {
//         id: 201,
//         title: 'Beyond Good and Evil',
//         subtitle: 'Prelude to a Philosophy of the Future',
//         publication_year: 1886,
//         publisher: 'C. G. Naumann',
//         description:
//           "Nietzsche's critique of past philosophers and traditional morality.",
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'read',
//         rating: 5,
//         location: 'Shelf C2',
//       },
//       {
//         id: 202,
//         title: 'Being and Time',
//         subtitle: 'An Inquiry Into Being',
//         publication_year: 1927,
//         publisher: 'Max Niemeyer',
//         description:
//           "Heidegger's fundamental investigation into the meaning of Being.",
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'unread',
//         rating: 0,
//         location: 'Shelf C3',
//       },
//       {
//         id: 203,
//         title: 'Critique of Pure Reason',
//         subtitle: 'The Limits of Knowledge',
//         publication_year: 1781,
//         publisher: 'Johann Friedrich Hartknoch',
//         description:
//           "Kant's investigation into the nature and limits of human knowledge.",
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'reading',
//         rating: 3,
//         location: 'Shelf C4',
//       },
//       {
//         id: 204,
//         title: 'Thus Spoke Zarathustra',
//         subtitle: 'A Book for All and None',
//         publication_year: 1883,
//         publisher: 'Ernst Schmeitzner',
//         description:
//           "Nietzsche's philosophical novel about the death of God and the Übermensch.",
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'read',
//         rating: 4,
//         location: 'Shelf C5',
//       },
//       {
//         id: 205,
//         title: 'The Art of War',
//         subtitle: 'Ancient Military Wisdom',
//         publication_year: -500,
//         publisher: 'Unknown',
//         description:
//           "Sun Tzu's classic treatise on military strategy and leadership.",
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'read',
//         rating: 5,
//         location: 'Shelf C6',
//       },
//       {
//         id: 206,
//         title: 'Ethics',
//         subtitle: 'Demonstrated in Geometrical Order',
//         publication_year: 1677,
//         publisher: 'Unknown',
//         description: "Spinoza's systematic exposition of reality and ethics.",
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'unread',
//         rating: 0,
//         location: 'Shelf C7',
//       },
//       {
//         id: 207,
//         title: 'The Prince',
//         subtitle: 'On Political Power',
//         publication_year: 1532,
//         publisher: "Antonio Blado d'Asola",
//         description:
//           "Machiavelli's famous treatise on political philosophy and statecraft.",
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'read',
//         rating: 4,
//         location: 'Shelf C8',
//       },
//       {
//         id: 208,
//         title: 'Phenomenology of Spirit',
//         subtitle: 'The Journey of Consciousness',
//         publication_year: 1807,
//         publisher: 'Joseph Anton Goebhardt',
//         description:
//           "Hegel's exploration of the evolution of consciousness and knowledge.",
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'unread',
//         rating: 0,
//         location: 'Shelf C9',
//       },
//       {
//         id: 209,
//         title: 'The Second Sex',
//         subtitle: 'A Study of Woman',
//         publication_year: 1949,
//         publisher: 'Gallimard',
//         description:
//           "Beauvoir's groundbreaking analysis of women's oppression.",
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'reading',
//         rating: 4,
//         location: 'Shelf C10',
//       },
//       {
//         id: 301,
//         title: 'Cloud Atlas',
//         subtitle: 'Six Lives Intertwined',
//         publication_year: 2004,
//         publisher: 'Sceptre',
//         description:
//           'An ambitious novel connecting six nested stories across time and space.',
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'read',
//         rating: 5,
//         location: 'Shelf D4',
//       },
//       {
//         id: 302,
//         title: 'The Brief Wondrous Life of Oscar Wao',
//         subtitle: 'A Dominican-American Story',
//         publication_year: 2007,
//         publisher: 'Riverhead Books',
//         description:
//           'A multi-generational story about a Dominican family and their curse.',
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'reading',
//         rating: 4,
//         location: 'Shelf D5',
//       },
//     ],
//   },{
//     id: 3,
//     name: 'Modern Fiction Favorites',
//     description: 'Bestselling novels from the 21st century.',
//     books: [
//       {
//         id: 5,
//         title: 'The Road',
//         subtitle: 'A Post-Apocalyptic Journey',
//         publication_year: 2006,
//         publisher: 'Alfred A. Knopf',
//         description:
//           'A bleak yet beautiful story of a father and son struggling to survive in a ruined world.',
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'read',
//         rating: 5,
//         location: 'Shelf D2',
//       },
//       {
//         id: 6,
//         title: 'The Night Circus',
//         subtitle: 'A Magical Love Story',
//         publication_year: 2011,
//         publisher: 'Doubleday',
//         description:
//           'A mesmerizing novel about a mysterious circus that only appears at night.',
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'unread',
//         rating: 0,
//         location: 'Shelf D3',
//       },

//       {
//         id: 303,
//         title: 'Life of Pi',
//         subtitle: 'Lost at Sea',
//         publication_year: 2001,
//         publisher: 'Knopf Canada',
//         description:
//           'A philosophical adventure about a boy stranded on a lifeboat with a tiger.',
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'read',
//         rating: 4,
//         location: 'Shelf D6',
//       },
//       {
//         id: 304,
//         title: 'Never Let Me Go',
//         subtitle: 'A Beautiful Tragedy',
//         publication_year: 2005,
//         publisher: 'Faber and Faber',
//         description:
//           'A haunting tale about the dark side of medical advancement.',
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'unread',
//         rating: 0,
//         location: 'Shelf D7',
//       },
//       {
//         id: 305,
//         title: 'The Book Thief',
//         subtitle: 'Words in War',
//         publication_year: 2005,
//         publisher: 'Picador',
//         description:
//           'A story about a young girl in Nazi Germany, narrated by Death.',
//         cover_image_url: 'https://via.placeholder.com/150',
//         status: 'read',
//         rating: 5,
//         location: 'Shelf D8',
//       },
//     ],
//   },
